
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVE_H
#define TESTSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlave_Data;
extern UNS32 pdo_m2s_rx_data;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS32 pdo_s2m_tx_data;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 sdo_m2s_rx_array[10];		/* Mapped at index 0x2002, subindex 0x01 - 0x0A */
extern UNS32 sdo_s2m_tx_array[10];		/* Mapped at index 0x2003, subindex 0x01 - 0x0A */
extern UNS8* sdo_version[1];		/* Mapped at index 0x2004, subindex 0x01 - 0x01 */
extern UNS32 sdo_version2[18];		/* Mapped at index 0x2005, subindex 0x01 - 0x12 */
extern UNS32 pdo1_rx2;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS32 pdo2_rx1;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS32 pdo2_rx2;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS32 pdo1_tx2;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS32 pdo2_tx1;		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS32 pdo2_tx2;		/* Mapped at index 0x200B, subindex 0x00*/
extern UNS16 sdo_cpu_id[8];		/* Mapped at index 0x200C, subindex 0x01 - 0x08 */

#endif // TESTSLAVE_H
